// Mock data for chat application

export const currentUser = {
  id: "u1",
  name: "My Account",
  avatar:
    "https://ui-avatars.com/api/?name=My+Account&background=df0b0b&color=fff",
  phone: "+1 234 567 8900",
  status: "online",
};

export const chats = [
  {
    id: "c1",
    contactId: "u2",
    lastMessage: "Hey, how are you doing?",
    lastMessageTime: "10:30 AM",
    unreadCount: 2,
    isPinned: true,
    isMuted: false,
    contact: {
      id: "u2",
      name: "John Doe",
      avatar:
        "https://ui-avatars.com/api/?name=John+Doe&background=22C55E&color=fff",
      status: "online",
      lastSeen: "online",
    },
  },
  {
    id: "c2",
    contactId: "u3",
    lastMessage: "Can we meet tomorrow?",
    lastMessageTime: "9:15 AM",
    unreadCount: 0,
    isPinned: true,
    isMuted: false,
    contact: {
      id: "u3",
      name: "Alice Smith",
      avatar:
        "https://ui-avatars.com/api/?name=Alice+Smith&background=df0b0b&color=fff",
      status: "offline",
      lastSeen: "last seen today at 8:30 AM",
    },
  },
  {
    id: "c3",
    contactId: "u4",
    lastMessage: "Thanks for your help!",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    isPinned: false,
    isMuted: true,
    contact: {
      id: "u4",
      name: "Bob Johnson",
      avatar:
        "https://ui-avatars.com/api/?name=Bob+Johnson&background=FB8B24&color=fff",
      status: "offline",
      lastSeen: "last seen yesterday at 6:45 PM",
    },
  },
  {
    id: "c4",
    contactId: "u5",
    lastMessage: "The project looks great! 🎉",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    contact: {
      id: "u5",
      name: "Team Work",
      avatar:
        "https://ui-avatars.com/api/?name=Team+Work&background=6C63FF&color=fff",
      status: "group",
      members: ["John", "Alice", "Bob", "You"],
    },
  },
  {
    id: "c5",
    contactId: "u6",
    lastMessage: "See you at the party!",
    lastMessageTime: "Monday",
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    contact: {
      id: "u6",
      name: "Sarah Wilson",
      avatar:
        "https://ui-avatars.com/api/?name=Sarah+Wilson&background=4F5D75&color=fff",
      status: "offline",
      lastSeen: "last seen Monday at 3:20 PM",
    },
  },
  {
    id: "c6",
    contactId: "u7",
    lastMessage: "Did you see the new design?",
    lastMessageTime: "Monday",
    unreadCount: 3,
    isPinned: false,
    isMuted: false,
    contact: {
      id: "u7",
      name: "Mike Brown",
      avatar:
        "https://ui-avatars.com/api/?name=Mike+Brown&background=3B82F6&color=fff",
      status: "online",
      lastSeen: "online",
    },
  },
];

export const messages = {
  c1: [
    {
      id: "m1",
      senderId: "u2",
      text: "Hey! How are you doing? 👋",
      time: "10:15 AM",
      status: "read",
      type: "text",
    },
    {
      id: "m2",
      senderId: "u1",
      text: "Hi John! I'm doing great! How about you?",
      time: "10:18 AM",
      status: "read",
      type: "text",
    },
    {
      id: "m3",
      senderId: "u2",
      text: "Pretty good! Just finished a big project.",
      time: "10:20 AM",
      status: "read",
      type: "text",
    },
    {
      id: "m4",
      senderId: "u2",
      text: "Hey, how are you doing?",
      time: "10:30 AM",
      status: "delivered",
      type: "text",
    },
  ],
  c2: [
    {
      id: "m1",
      senderId: "u3",
      text: "Hey! Are you free tomorrow?",
      time: "9:00 AM",
      status: "read",
      type: "text",
    },
    {
      id: "m2",
      senderId: "u1",
      text: "Hi Alice! Let me check my schedule...",
      time: "9:05 AM",
      status: "read",
      type: "text",
    },
    {
      id: "m3",
      senderId: "u1",
      text: "Yes, I should be free after 2 PM.",
      time: "9:07 AM",
      status: "read",
      type: "text",
    },
    {
      id: "m4",
      senderId: "u3",
      text: "Can we meet tomorrow?",
      time: "9:15 AM",
      status: "read",
      type: "text",
    },
  ],
  c3: [
    {
      id: "m1",
      senderId: "u1",
      text: "Hey Bob, I need help with the React component.",
      time: "Yesterday 2:00 PM",
      status: "read",
      type: "text",
    },
    {
      id: "m2",
      senderId: "u4",
      text: "Sure! What do you need help with?",
      time: "Yesterday 2:15 PM",
      status: "read",
      type: "text",
    },
    {
      id: "m3",
      senderId: "u1",
      text: "I'm trying to set up the state management.",
      time: "Yesterday 2:20 PM",
      status: "read",
      type: "text",
    },
    {
      id: "m4",
      senderId: "u4",
      text: "No problem. Let me share my screen.",
      time: "Yesterday 2:30 PM",
      status: "read",
      type: "text",
    },
    {
      id: "m5",
      senderId: "u4",
      text: "Thanks for your help!",
      time: "Yesterday 4:00 PM",
      status: "read",
      type: "text",
    },
  ],
  c4: [
    {
      id: "m1",
      senderId: "u2",
      text: "Team, the new design is ready for review!",
      time: "Yesterday 10:00 AM",
      status: "read",
      type: "text",
    },
    {
      id: "m2",
      senderId: "u3",
      text: "Great work @John! It looks amazing! 🔥",
      time: "Yesterday 10:15 AM",
      status: "read",
      type: "text",
    },
    {
      id: "m3",
      senderId: "u4",
      text: "I love the color scheme! 👍",
      time: "Yesterday 10:30 AM",
      status: "read",
      type: "text",
    },
    {
      id: "m4",
      senderId: "u1",
      text: "The project looks great! 🎉",
      time: "Yesterday 11:00 AM",
      status: "read",
      type: "text",
    },
  ],
  c5: [
    {
      id: "m1",
      senderId: "u6",
      text: "Hey! Are you coming to the party this weekend?",
      time: "Monday 6:00 PM",
      status: "read",
      type: "text",
    },
    {
      id: "m2",
      senderId: "u1",
      text: "Yes! What time does it start?",
      time: "Monday 6:15 PM",
      status: "read",
      type: "text",
    },
    {
      id: "m3",
      senderId: "u6",
      text: "It starts at 8 PM.",
      time: "Monday 6:20 PM",
      status: "read",
      type: "text",
    },
    {
      id: "m4",
      senderId: "u1",
      text: "See you at the party!",
      time: "Monday 6:30 PM",
      status: "read",
      type: "text",
    },
  ],
  c6: [
    {
      id: "m1",
      senderId: "u7",
      text: "Hey! Check out the new design I made.",
      time: "Monday 2:00 PM",
      status: "read",
      type: "text",
    },
    {
      id: "m2",
      senderId: "u7",
      text: "https://figma.com/file/abc123",
      time: "Monday 2:05 PM",
      status: "read",
      type: "link",
    },
    {
      id: "m3",
      senderId: "u1",
      text: "This looks awesome!",
      time: "Monday 2:30 PM",
      status: "read",
      type: "text",
    },
    {
      id: "m4",
      senderId: "u7",
      text: "Did you see the new design?",
      time: "Monday 3:00 PM",
      status: "delivered",
      type: "text",
    },
  ],
};
